/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as openzeppelinContracts from "./openzeppelin-contracts";
import type * as openzeppelinContractsUpgradeable from "./openzeppelin-contracts-upgradeable";

export type { openzeppelinContracts };

export type { openzeppelinContractsUpgradeable };
